FROM phpdockerio/php:8.1-fpm

WORKDIR "/app"

RUN apt-get update; \
    apt-get -y --no-install-recommends install \
        nodejs npm \
        php8.1-imagick \
        php8.1-mysql \
        php8.1-redis \
        php8.1-xdebug; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
